/*
 * ================================================================
 *
 * Filename:    stats.cpp
 *
 * Description: Reads integer exam scores from stdin and prints a
 *              summary: count, minimum, maximum, and mean.
 *
 * Created:     08/26/2026
 * EID:         ap62929
 * Email:       ap62929@my.utexas.edu
 * Author:      Ayushi Priyadarshani
 * Provenance:  I certify that all code contained herein is mine
 *              alone except where otherwise noted.
 *
 * ================================================================
 */

/*
 * ECE 412 -- Lab 0 -- starter code
 *
 * WHAT TO DO
 *   Fill in the four functions below and the body of main. Everything
 *   marked TODO is yours; nothing else needs to change.
 *
 * BUILD AND RUN
 *   make
 *   ./stats < sample.txt
 *   ./stats < /dev/null
 *
 * REQUIRED OUTPUT, exactly this format:
 *
 *   Count: 5
 *   Min: 62
 *   Max: 95
 *   Mean: 79.40
 *
 *   On empty input, print "Count: 0" and nothing else, then exit 0.
 *   Mean prints to exactly two decimal places.
 *
 * RULES FOR THIS WEEK
 *   - C-compatible subset of C++11. <cstdio> and raw arrays only.
 *   - BANNED: std::cout / std::cin, std::string, std::vector, classes,
 *     member functions, references (T&), new/delete, malloc, templates,
 *     auto, range-for, the STL.
 *   - No global variables. Not one.
 *   - main orchestrates only: read input, call helpers, print.
 *   - Compiles with zero warnings under -Wall -Wextra -Werror.
 *
 * AI USE
 *   If you use an assistant, put a citation block immediately above any
 *   code you did not write yourself:
 *
 *     /_* Lines NN-MM were generated by the AI tool <Tool name>.
 *        The purpose of this code is ... *_/
 *
 *   (Written with underscores here only so it does not close this
 *   comment. Use the normal form in your own code.)
 */

#include <cstdio>

#define MAX_SCORES 1000

/*
 * Description:        Reads integers from stdin until end of input or the
 *                     first token that is not an integer.
 * Input parameters:   int *scores: array to fill
 *                     int capacity: maximum number of values to store
 * Return value:       int: how many values were actually read
 * In/Out parameters:  scores is filled in by this function
 *
 * Hints:
 *   - Use scanf("%d", &x) in a loop and check that it returns 1.
 *     A return of 1 means "I got an integer." Anything else ends the loop.
 *   - Stop once you have read `capacity` values. Do not write past the end
 *     of the array.
 */
int read_scores(int *scores, int capacity) {
    /* TODO: implement. Remove the two (void) lines once you use the
       parameters -- they exist only so the starter compiles cleanly. */
    for (int i = 0; i < capacity; i++) {
        if (scanf("%d", &scores[i]) != 1) {
            return i; 
        }
    }
    
    return 0;
}

/*
 * Description:        Smallest value in the array.
 * Input parameters:   const int *scores: the values
 *                     int n: how many values there are (n >= 1)
 * Return value:       int: the minimum
 * In/Out parameters:  None
 *
 * Hint: start from scores[0], not from 0. A score of 0 is a legal value,
 *       and scores can be negative.
 */
int min_of(const int *scores, int n) {
    /* TODO: implement */
    int min = scores[0];
    for(int i = 1; i < n; i++){
        if(scores[i] < min){
            min = scores[i];
        }
    }
    return min;
}

/*
 * Description:        Largest value in the array.
 * Input parameters:   const int *scores: the values
 *                     int n: how many values there are (n >= 1)
 * Return value:       int: the maximum
 * In/Out parameters:  None
 */
int max_of(const int *scores, int n) {
    /* TODO: implement */
    int max = scores[0];    
    for(int i = 0; i < n; i++){
        if (scores[i] > max){
            max = scores[i];
        }
    }

    return max;
}

/*
 * Description:        Arithmetic mean of the array.
 * Input parameters:   const int *scores: the values
 *                     int n: how many values there are (n >= 1)
 * Return value:       double: the mean
 * In/Out parameters:  None
 *
 * Hint: sum / n with two ints is INTEGER division and throws away the
 *       fraction. Cast deliberately.
 */
double mean(const int *scores, int n) {
    /* TODO: implement */
    (void)scores;
    (void)n;
    double sum = 0.0;
    for(int i = 0; i < n; i++){
        sum += scores[i];
    }

    return sum / (double)n;
}

int main(void) {
    int scores[MAX_SCORES];
    int n = read_scores(scores, MAX_SCORES);

    printf("Count: %d\n", n);
    if (n == 0) {
        return 0;
    }

    /* TODO: print Min, Max and Mean, in that order, by calling the
       functions above. Match the format shown at the top of this file. */
    printf("Min: %d\n", min_of(scores, n));
    printf("Max: %d\n", max_of(scores, n)); 
    printf("Mean: %.2f\n", mean(scores, n));
    return 0;
}
